BristolTopGroup/AnalysisSoftware

interface/HistHelpers/HistogramManager.h
src/Analysers/Binned_variable_analyser.cpp
src/Analysers/TTbar_plus_X_analyser.cpp
src/HistHelpers/HistogramManager.cpp
src/Readers/NTupleEventReader.cpp
test/TestBinnedVariableAnalyser.cpp

[MRG] Binned variable analyser upgrade [Run2]

---

condor/condor.sh
condor/job_mapper

Add option in condor scripts to run all samples for one analysis mode.

---

CMakeLists.txt
README.md
python/DataSetInfo_7TeV.py
python/DataSetInfo_8TeV.py
src/Analysers/METAnalyser.cpp
src/Analysers/TTbar_plus_X_analyser.cpp
test/boostTests.cpp

**Build**
- added PROJECT_LIB_NAME and dependencies for unit tests to CMakeLists.txt
**Documentation**
- git  submodule
- test binary (might not work in all CMSSW versions)
**Analysis**
- updated 7 & 8 TeV ttbar cross sections
- added control plots to MET analyser (MET_vs_leptonPt, MET_plus_leptonPt, MET_vs_leptonEta, andHT_vs_MET_plus_leptonPt
- updated bins for measurement (will be overwritten by @EmyrClement )

[MRG] Merge run1 into run2

---

bin/Analysis.cpp
condor/job_mapper
interface/BTagWeight.h
interface/Event.h
interface/Readers/NTupleEventReader.h
src/Analysers/JetAnalyser.cpp
src/Analysers/TTbar_plus_X_analyser.cpp
src/Analysers/UnfoldingRecoAnalyser.cpp
src/BTagWeight.cpp
src/Event.cpp
src/Readers/NTupleEventReader.cpp

B jet scale factors now calculated and stored in output.

Variables for measurement

---

bin/Analysis.cpp
interface/DataTypes.h
interface/Event.h
interface/Readers/NTupleEventReader.h
python/DataSetInfo_13TeV_50ns.py
python/analysis_info.py
python/master_2015_cfg.py
src/Analysers/TTbar_plus_X_analyser.cpp
src/Analysers/UnfoldingRecoAnalyser.cpp
src/Event.cpp
src/EventWeightProvider.cpp
src/Python/ConfigFile.cpp
src/Readers/JetReader.cpp
src/Readers/METReader.cpp
src/Readers/NTupleEventReader.cpp
src/Readers/TTGenReader.cpp
src/RecoObjects/Electron.cpp
src/RecoObjects/Jet.cpp
src/RecoObjects/Muon.cpp
test/TestBinnedVariableAnalyser.cpp

- Switch to METNoHF.  Will re-enable original MET for comparisons.
- Update lepton SF and JER
- Actually apply trigger selection for MC in QCD control region

Up to preapproval

---

src/Readers/NTupleEventReader.cpp

Remove type = debug BJetUp/Down Problem

---

src/Analysers/TTbar_plus_X_analyser.cpp

Jet pt was only being stored for the lowest pt jet in the event.  Now, all jets are stored.  Also added eta of these jets.

Jet variables

---

src/Readers/ElectronReader.cpp
src/Readers/SelectionOutputReader.cpp

Remove mvaTrig Electron ID
Fix SelectionReader

Remove electron mva readers, Fix Selection Reader

---

src/Analysers/PseudoTopAnalyser.cpp
src/Event.cpp
src/Readers/NTupleEventReader.cpp
src/RecoObjects/Electron.cpp

-Increase offline lepton pt threshold (was below trigger)
-Modify visible phase space cuts
-Update electron SF treatment
No trigger SF, so just apply id and iso SF.
Do not apply electron trigger in MC for now.

Leptons again

---

condor/job.sh
condor/job_mapper
python/analysis_info_2016.py

Update CMSSW in condor
Update how it finds number of files
Correct the dataset input file

For condor to work

---

python/DataSetInfo_13TeV_25ns.py
python/analysis_info_2016.py
python/get_number_of_processed_events.py
python/master_2015_cfg.py

Update DataSetInfo
Comment calculator of which data ntuple have been processed out
Remove amcatnloherwig from analysis_info
Fix AS ntuple naming when jobs are split

Renew DataSetInfo.

---

condor/job_mapper
interface/Event.h
interface/Readers/NTupleEventReader.h
src/Analysers/UnfoldingRecoAnalyser.cpp
src/Event.cpp
src/Readers/NTupleEventReader.cpp

Distinguish between pdf, alphas, and factorisation/renormalisation generator weights.
Also fix bug in job_mapper from previous PR.

Pdf systematic

---

interface/Readers/JetReader.h
interface/RecoObjects/Jet.h
src/Readers/JetReader.cpp
src/RecoObjects/Jet.cpp

Reverts BristolTopGroup/AnalysisSoftware#224
Will not work until new ntuple arrive.

Revert "Scaling+Stochastic JER"

---

interface/DataTypes.h
python/DataSetInfo_13TeV_25ns.py
python/analysis_info_2016.py
src/Event.cpp
src/Python/ConfigFile.cpp

madgraph now uses its old name

reinstate madgraphMLM

---

src/Analysers/TTbar_plus_X_analyser.cpp

Seg fault sometimes happens here, seen in Powheg+Herwig and in JES_down Powheg+Pythia.  These variables were experimental, and not used in the analysis, so we can comment out for now.

Remove section causing seg fault

---

interface/Readers/ElectronReader.h
interface/RecoObjects/Lepton.h
python/analysis_info_2016.py
src/Analysers/TTbar_plus_X_analyser.cpp
src/Event.cpp
src/Readers/ElectronReader.cpp
src/RecoObjects/Lepton.cpp

- Read and store hlt isolation variables for electrons
- Cut on hlt isolation of electrons in non isolated control region

Electron qcd selection

---

interface/Readers/PseudoTopReader.h
src/Analysers/PseudoTopAnalyser.cpp
src/Readers/PseudoTopReader.cpp

Read pseudoTopMET
Replace GenMET with pseudoTopMET in pseudoTop analyser.
No set of ntuples with pseudoTopMET is available yet, tested on small file
(/scratch/db0268/NTP/NTP_8026/NTupleProduction/workspace/results/TTJets_PowhegPythia8_Moriond17_ntuple.root)

Swap to MET from pseudoTop

---

interface/Readers/PseudoTopReader.h
python/DataSetInfo_13TeV_25ns.py
python/analysis_info_2016.py
src/Analysers/TTbar_plus_X_analyser.cpp
src/Readers/PseudoTopReader.cpp

- Read in new PseudoTop MET
- Add more vars to the NoB trees for debugging
- Update ntuple number and number of processed events for tt samples

Pseudo top

---

interface/Analysers/TTbar_plus_X_analyser.h
interface/Analysers/WAnalyser.h
src/Analysers/TTbar_plus_X_analyser.cpp
src/Analysers/WAnalyser.cpp

Essentially removed the old (outdated) code, and replaced with a simpler version.

Add back the simple W mass analyser

---

interface/Analysers/PseudoTopAnalyser.h
interface/DataTypes.h
interface/Event.h
python/DataSetInfo_13TeV_25ns.py
python/analysis_info_2016.py
src/Analysers/PseudoTopAnalyser.cpp
src/Analysers/TTbar_plus_X_analyser.cpp
src/Analysers/WAnalyser.cpp
src/Event.cpp

Store the info for an alternative phase space definition
Instead of requiring 4 jets with pt > 30 GeV, 2 of which are b jets, the alternative phase space requires 3 jets with pt > 30 GeV, and 1 jet with pt > 20 GeV.  Two of these jets must be b jets.
An additional bool for passing this phase space is stored, along with HT, ST, and NJets calculated for jet pt > 20 GeV.

Phase space study

---

interface/BTagWeight.h
interface/Event.h
python/DataSetInfo_13TeV_25ns.py
python/analysis_info_2016.py
src/Analysers/TTbar_plus_X_analyser.cpp
src/Analysers/UnfoldingRecoAnalyser.cpp
src/BTagWeight.cpp
src/Event.cpp
src/Readers/NTupleEventReader.cpp

- Store several possible b tag weights and corrections
- New input file/number of processed events

B tag corrections
